Increase unit testing for container spec
ccontreras/InjectJS pull request #2
Opened 2018-08-19 23:22 UTC by edjroz

- Make the Get container function return immutable Object
- remove all items from container

2018-08-20 04:25 UTC, ccontreras requested changes
Hey nice contribution dude :100: !,
I left some suggestions, once they are corrected then I'll proceed merging.

2018-08-20 04:25 UTC, ccontreras commented on src/container.js
> +  Object.keys(container).forEach(k => delete container[k]);
You could reset the container instead. like this:
`container = {}`
it would be more efficient

2018-08-20 04:25 UTC, ccontreras commented on src/container.spec.js
> +    const newKey = getKey(1);
It seems `newKey` is not being used anywhere.

2018-08-20 12:50 UTC, edjroz commented on src/container.js
> +  Object.keys(container).forEach(k => delete container[k]);
In order to do this Ill have to change the container variable from a const to a let. Also y doing this I can add a `freeze` function that makes the variable immutable for change

2018-08-23 14:29 UTC, ccontreras commented on src/container.js
> +  Object.keys(container).forEach(k => delete container[k]);
Sure!, go ahead!

2018-08-30 17:48 UTC, ccontreras approved these changes

2018-08-30 17:49 UTC, merged